### ISSUE TITLE
Large Code Values Displayed with Commas cause issues in Exported .CSV File

### ISSUE THREAD

**Issue by missdrewbaxter** [mblsolutions/report#20]
On this report:
https://staging-admin.inspireddeck.co.uk/report/10

The data has values with commas in, e.g.:

Redu | Debit | 4491 | 123,484.37 | Voucher

The 123,485.37 value causes issue with the csv export if you press yes to formatting the results, as it would then put the 484.37 in another column on the spreadsheet as it has a comma.

This doesn't happen on the non-formatted version of export.

**Comment by missdrewbaxter** [comment]
Also on code debits, I imagine this will be the case across all reports.

**Comment by sawinfield** [comment]
This is going to be an issue on all of these reports as you say. I don't think there is away around the commas in the export file unless coded as such. The fields should really be either encapsulated by quotes or a choice of delimited (e.g. TAB, which is not a natural field value).

**Comment by sawinfield** [comment]
Code 1006 on staging has £2000 credited to it to demonstrate. Locale may have effect on this.

**Comment by lerouse** [comment]
Fixed as part of v2.x
